/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewRouteImport } from './routes/new'
import { Route as StudioBookIdRouteImport } from './routes/studio.$bookId'
import { Route as ApiAiCompleteRouteImport } from './routes/api/ai.complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioBookIdRoute = StudioBookIdRouteImport.update({
  id: '/studio/$bookId',
  path: '/studio/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCompleteRoute = ApiAiCompleteRouteImport.update({
  id: '/api/ai/complete',
  path: '/api/ai/complete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/studio/$bookId': typeof StudioBookIdRoute
  '/api/ai/complete': typeof ApiAiCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/studio/$bookId': typeof StudioBookIdRoute
  '/api/ai/complete': typeof ApiAiCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/new': typeof NewRoute
  '/studio/$bookId': typeof StudioBookIdRoute
  '/api/ai/complete': typeof ApiAiCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/new' | '/studio/$bookId' | '/api/ai/complete'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/new' | '/studio/$bookId' | '/api/ai/complete'
  id: '__root__' | '/' | '/new' | '/studio/$bookId' | '/api/ai/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewRoute: typeof NewRoute
  StudioBookIdRoute: typeof StudioBookIdRoute
  ApiAiCompleteRoute: typeof ApiAiCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$bookId': {
      id: '/studio/$bookId'
      path: '/studio/$bookId'
      fullPath: '/studio/$bookId'
      preLoaderRoute: typeof StudioBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/complete': {
      id: '/api/ai/complete'
      path: '/api/ai/complete'
      fullPath: '/api/ai/complete'
      preLoaderRoute: typeof ApiAiCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewRoute: NewRoute,
  StudioBookIdRoute: StudioBookIdRoute,
  ApiAiCompleteRoute: ApiAiCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
